#!/usr/bin/python3
import time, rclpy
from rclpy.node import Node

from geometry_msgs.msg import Twist, TwistStamped

def main(args=None):
    # Initialize ROS
    rclpy.init(args=args)

    # Initialize ScanInterperter
    node = Multiplexer()
    
    # infinite Loop
    rclpy.spin(node)
    
    # Clean end
    node.destroy_node()
    rclpy.shutdown()

class MapServer(Node):

    def __init__( self ):
        super().__init__('map_server')
        
        self.create_subscription( Twist, topic, callback, 10)
        
        self._cmdSimplePub= self.create_publisher( Twist, 'cmd_simple_vel', 10)
        self._cmdStampPub= self.create_publisher( TwistStamped, 'cmd_spamped_vel', 10)

    def activateSecurity(self):
        self.create_timer(0.1, self.cmd_0)

    # CallBack gestion:
    def cmd_callback(self, prevalence, cmdMsg):
        t= time.time() # ToDO: t= self.get_clock().now()
        if prevalence >= self.hand or t - self.t > 1.0 :
            if prevalence > self.hand :
                self.get_logger().info( f"Get cmd from {prevalence}" )
            self.hand= prevalence
            self.t= t
            self._cmdSimplePub.publish( cmdMsg )

            stampedCmd= TwistStamped()
            stampedCmd.twist= cmdMsg
            stampedCmd.header.frame_id= "base_footprint"
            stampedCmd.header.stamp= self.get_clock().now().to_msg()
            self._cmdStampPub.publish( stampedCmd )

    def cmd_0(self):
        velo= Twist()
        return self.cmd_callback(0, velo)

    def cmd_1_callback(self, cmdMsg):
        return self.cmd_callback(1, cmdMsg)
    
    def cmd_2_callback(self, cmdMsg):
        return self.cmd_callback(2, cmdMsg)

    def cmd_3_callback(self, cmdMsg):
        return self.cmd_callback(3, cmdMsg)

    def cmd_4_callback(self, cmdMsg):
        return self.cmd_callback(4, cmdMsg)

    def cmd_5_callback(self, cmdMsg):
        return self.cmd_callback(5, cmdMsg)

    def cmd_6_callback(self, cmdMsg):
        return self.cmd_callback(6, cmdMsg)

    def cmd_7_callback(self, cmdMsg):
        return self.cmd_callback(7, cmdMsg)

    def cmd_8_callback(self, cmdMsg):
        return self.cmd_callback(8, cmdMsg)

if __name__ == "__main__" :
    main()