#!/usr/bin/python3
import os, rclpy
from rclpy.node import Node
from std_msgs.msg import String
def main():
    monitor= Basic()
    monitor.process()

class Basic():
    running= [ " ", " ", "▖", "▖", "▌", "▛", "█", "▜", "▐", "▐", "▗", "▗" ]
    runlen= len( running )

    def __init__(self):
        self._i= 0
        self._pulses= {}

    def monitor_callback(self):
        os.system('clear')
        print( Basic.running[self._i]+" Pulse Monitor: ")
        self._i= (self._i+1)%Basic.runlen
        for p in self._pulses :
            pulse_str= ""
            for i in range(len(p), 12) :
                pulse_str+= " "
            pulse_str+= p + ": "
            
            pulse_str+= self._pulses[p][1] + " " + self._pulses[p][0]
            if self._i%3 == 0 :
                self._pulses[p][1]= self._pulses[p][1][1:] + "–"

            print( pulse_str )
        
    def pulse_callback(self, msg):
        pulse= msg.data.split(": ")
        organism= pulse[0]
        status= pulse[1]
        if organism in self._pulses :
            self._pulses[organism][0]= status
            self._pulses[organism][1]= self._pulses[organism][1][:-1]+"⥍"
        else :
            self._pulses[organism]= [ status, "––––––––⥍"]

    def process(self):
        # Ros initialization
        rclpy.init(domain_id= 100)
        node = Node( f"pulse_monitor" )
        self._timer = node.create_timer( 0.05, self.monitor_callback )
        node.create_subscription( String, "pulse", self.pulse_callback, 10 )
        # Infinite loop:
        rclpy.spin(node)

        # Clean stop:
        node.destroy_node()
        rclpy.shutdown()

if __name__ == '__main__':
    main()